### ISSUE TITLE
MMG Error Report

### ISSUE THREAD

**Issue by echoi** [tan2/DynEarthSol#14]
We are facing a problem when using MMG remesh. We have documented the environment, code version, input files, and output message of our test. I hope this information can help you reproduce the error.

Thanks for your time and help.

Best regards,
@chaseshyu 

### Compiler and dependencies
- [gcc 8.4](https://gcc.gnu.org/onlinedocs/8.4.0/)
- [Boost 1.81.0](https://www.boost.org/users/history/version_1_81_0.html)
- [MMG](https://github.com/MmgTools/mmg.git)
  - Sha1: 433519f2e628ab4ecd234d66d8e2a1d4cc9f8125
  - With: `CMAKE_C_FLAGS = -std=c11`

#### Diff:
  1. [bc.cxx.diff.txt](https://github.com/tan2/DynEarthSol/files/13392578/bc.cxx.diff.txt)
  2. [remeshing.cxx.diff.txt](https://github.com/tan2/DynEarthSol/files/13392577/remeshing.cxx.diff.txt)
Note: `.txt` added to comply with the github's uploadable file types.

#### Command to the modified des code
```BASH
$ git clone https://github.com/chaseshyu/DynEarthSol.git
$ cd DynEarthSol
$ git checkout 7c231a7bf72cddd5c3739e1d8a7821fef5b7ebd8
$ git apply bc.cxx.diff
$ git apply remeshing.cxx.diff
```
#### Compile command:
`make ndims=2 usemmg=1`

#### Input files
- [v22v17G2f30r500L.cfg.txt](https://github.com/tan2/DynEarthSol/files/13392619/v22v17G2f30r500L.cfg.txt)
- [3km_3kmL.poly.txt](https://github.com/tan2/DynEarthSol/files/13392618/3km_3kmL.poly.txt)
Note: `.txt` added to comply with the github's uploadable file types.

#### Environment
- CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
- CUP core#: 16 cores

#### Output and Error Message
```BASH
[chaseshyu@c25g02 mmg_test]$ ../../dynearthsol2d v22v17G2f30r500L.cfg 
Checking consistency of input parameters...
Initializing mesh and field data...
  Output # 0, step = 0, time = 0 yr, dt = 0.100344 yr, wt = 000:00:00.079123
Starting simulation...
  Output # 1, step = 9966, time = 1000.032386 yr, dt = 0.100344 yr, wt = 000:00:11.019593
  Output # 2, step = 19932, time = 2000.064771 yr, dt = 0.100344 yr, wt = 000:00:21.898881
  Output # 3, step = 29898, time = 3000.097157 yr, dt = 0.100344 yr, wt = 000:00:32.770712
  Output # 4, step = 39863, time = 4000.029198 yr, dt = 0.100344 yr, wt = 000:00:43.645355
  Output # 5, step = 49829, time = 5000.061583 yr, dt = 0.100344 yr, wt = 000:00:54.528560
  Output # 6, step = 59795, time = 6000.093969 yr, dt = 0.100344 yr, wt = 000:01:05.414158
  Output # 7, step = 69760, time = 7000.026010 yr, dt = 0.100344 yr, wt = 000:01:16.288669
  Output # 8, step = 79726, time = 8000.058396 yr, dt = 0.100344 yr, wt = 000:01:27.176308
  Output # 9, step = 89692, time = 9000.090781 yr, dt = 0.100344 yr, wt = 000:01:38.069620
  Output # 10, step = 99657, time = 10000.022822 yr, dt = 0.100344 yr, wt = 000:01:48.968671
  Output # 11, step = 109623, time = 11000.055208 yr, dt = 0.100344 yr, wt = 000:01:59.866231
  Output # 12, step = 119589, time = 12000.087593 yr, dt = 0.100344 yr, wt = 000:02:10.758091
  Output # 13, step = 129554, time = 13000.019634 yr, dt = 0.100344 yr, wt = 000:02:21.641532
  Output # 14, step = 139520, time = 14000.052020 yr, dt = 0.100344 yr, wt = 000:02:32.545510
  Output # 15, step = 149486, time = 15000.084406 yr, dt = 0.100344 yr, wt = 000:02:43.454836
  Output # 16, step = 159451, time = 16000.016447 yr, dt = 0.100344 yr, wt = 000:02:54.359083
  Output # 17, step = 169417, time = 17000.048832 yr, dt = 0.100344 yr, wt = 000:03:05.272767
  Output # 18, step = 179383, time = 18000.081218 yr, dt = 0.100344 yr, wt = 000:03:16.188001
  Output # 19, step = 189348, time = 19000.013259 yr, dt = 0.100344 yr, wt = 000:03:27.088567
  Output # 20, step = 199314, time = 20000.045645 yr, dt = 0.100344 yr, wt = 000:03:38.000404
  Output # 21, step = 209280, time = 21000.078030 yr, dt = 0.100344 yr, wt = 000:03:48.894818
    Element #3086 has mesh quality = 0.399994.
  Remeshing starts...
x1x: -1090.126662; bx0: -6000.000000

  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
   MODULE MMG2D: 5.7.0 (Dec. 13, 2022)
  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
     git branch: HEAD
     git commit: 433519f2e628ab4ecd234d66d8e2a1d4cc9f8125
     git date:   2023-09-17 12:41:34 +0200


   MMG2DLIB: ELAPSED TIME  0.086s

  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
   END OF MODULE MMG2D
  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

Updated mesh size
New number of vertices:4414
New number of elements:8244
New number of segments:582
Resized arrays
New coordinates populated
New connectivity populated
New segments populated
Arrays transferred.
MMG2D freed.

Mesh optimization done
    Interpolating fields.
    Remapping markers.
  Increasing marker arrays size to 50320 markers.
  Remeshing finished.
    The size of element #8175 is too small.
  Remeshing starts...
x1x: -1090.628562; bx0: -6000.000000

  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
   MODULE MMG2D: 5.7.0 (Dec. 13, 2022)
  &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
     git branch: HEAD
     git commit: 433519f2e628ab4ecd234d66d8e2a1d4cc9f8125
     git date:   2023-09-17 12:41:34 +0200

  ## Error: MMG2D_boulen: Unable to find a boundary edge in the ball of point 894.

  ## Error: MMG2D_norver: Impossible to calculate normal vector at vertex 894.

  ## Problem in calculating normal vectors. Exit program.
BAD ENDING OF MMG3DLIB
```

Chase Jhih-Huang Shyu (@chaseshyu)
徐 志煌
Ph.D. candidate
Taiwan International Graduate Program 
Institute of Earth Sciences 
Academia Sinica 
Taipei 11529, Taiwan 
Tel: +886-2-2783-9910 # 1500

**Comment by echoi** [comment]
I could reproduce the error.
- before remeshing
![before_remeshing](https://github.com/tan2/DynEarthSol/assets/5417526/abb05e01-454f-4da1-bab7-e70e561da2df)
- after remeshing
![after_remeshing](https://github.com/tan2/DynEarthSol/assets/5417526/e093d0a6-b632-4696-9056-c2eb386600cf)

This is one of the situations in which the current mesh optimization scheme is bound to fail.

The x coordinate of the two boundary nodes are reset to that of the black dashed line as indicated by the orange arrows.
Then, the green element penetrates the yellow elements causing problems to the mesh optimization algorithm.
![image01](https://github.com/tan2/DynEarthSol/assets/5417526/6616cff1-77ad-4343-a11d-65532e1d4a43)

One solution would be to remesh more frequently. For instance, if remeshed after the 8th output, the mesh will get normally optimized (see the screenshot below) although you might still get some small elements on the lower right corner.
![image02](https://github.com/tan2/DynEarthSol/assets/5417526/91952ed8-b008-494a-89fd-a09590e6e1a1)

Another solution would be to leave the boundary nodes where they are at the time of remeshing.

Cheers,
Eunseo

**Comment by echoi** [comment]
@chaseshyu wrote:

> Thanks for your detailed explanation.
We will try to continue the test with the solutions you provided and keep you updated.
Also, you helped us be aware of a potential problem that our modified remeshing code accidentally deletes an element during the remeshing.
This deletion might cause other issues in element management.

**Comment by echoi** [comment]
Sorry, I didn't get any notification on your new comment.

Do you mean remeshing is occurring at every time step? Since that was not the setup specified in your original input file, I don't understand exactly what is going on. 

I just played with the remeshing parameters in the original input file a little further and learned that `mean_quality` equal to 0.6 was sufficient to keep the model running.

Unfortunately, another issue arose. At some point, remeshing was repeated many times before resuming time marching again. The problem is that the repeated remeshing diffused the shear band too much, which was forming near the right boundary. The apparent reason was that an element size was too small: e.g., `The size of element #2146 is too small.` I think you would want to turn off that test in `bad_mesh_quality()` function when using `mmg` as a mesh optimizer.

**Comment by fyilee** [comment]
I've adopted your suggestion and set min_quality equal to 0.6. After meeting the same problem of repeated remeshing, I turned off the size test in remeshing.cxx. However, even without the size test, those small elements are also with bad mesh quality and lead to repeated remeshing.

I'll try to change the meshing parameters to set a less strict requirement in the following tests.

Thanks for your help!

**Comment by echoi** [comment]
You're welcome. I can see that you are about to get things working but please feel free to share your input parameters so that I can reproduce the latest issue.

**Comment by echoi** [comment]
I confirm that `mmg` does not work when an old mesh is modified in such a way that the internal consistency is broken. One example would be to delete nodes without updating connectivity as `flatten_bottom()` tries to do. 

However, `mmg` can still work in `optimize_mesh()` although this function does adjust boundaries according to the value of `remeshing_option`. When `remeshing_option = 11`, for instance, it flattens the bottom boundary and register nodes too close to the bottom for deletion. However, those in the `points_to_delete` array are never actually deleted in `optimize_mesh()`. This is why `mmg` works fine in the `core-complex-mmg` case with `remeshing_option = 11`. So, if you are deleting any nodes before remeshing, you would want to stop doing so to work with `mmg`. 

Remeshing is sufficiently frequent in the `core-comple-mmg` case . It is because `bad_mesh_quality()` function checks if 
> any bottom node is too far away from the bottom depth

when `remeshing_option = 11`. A similar check would be desirable for your right boundary. Since a velocity BC is applied on the right boundary, the check should be similar to but much simpler than the one for the bottom boundary.

**Comment by chaseshyu** [comment]
If the control parameter you suggested ```max_x0_dx```, max distance between x0 nodes and ```x0_ref``` (blue dashed line), is used as the threshold of remesh for  ```flatten_x0```, ```max_x0_dx``` would need to be smaller than the size of most right bottom segment  and be smaller than the distance between the closest internal nodes to the ```x0_ref``` and ```x0_ref```. The wrong ```max_x0_dx``` could result in a ```mmg``` remeshing error, which increse the dependence between parameters (element size and ```max_x0_dx```). 

In this case, I suggest ```flatten_x0``` just follows the original mesh quality checks. On the other hand, when remesh occurs, ```flatten_x0``` shrinks all nodes (red points) at the right hand side of ```b0_min```-```z0_max``` line (black dashed line) into the left hand side of ```x0_ref``` (blue points).
<img width="300" alt="flatten b0 for mmg" src="https://github.com/tan2/DynEarthSol/assets/5525742/82fbf581-e13c-450f-bf22-bce093da879e">

Movie
https://github.com/tan2/DynEarthSol/assets/5525742/c4b399db-0e0e-42f5-b1bf-1466c8a40048

However, I found this model has abnormal high remeshing frequency with ```mmg``` ```min_quality = 0.3```.
The high remeshing frequency resulted in diffusion of values of variables.
Remeshing message is ```The size of element #XXX is too small.```
<img width="600" alt="diffusion" src="https://github.com/tan2/DynEarthSol/assets/5525742/3a11d9bb-d845-4536-bc50-d7838106453d">

Movie 0 - 50 kyr
https://github.com/tan2/DynEarthSol/assets/5525742/c77f347e-48ce-41f1-a7d5-988310f93c6b

Movie 0 - 50 kyr ```has_output_during_remeshing = yes```
https://github.com/tan2/DynEarthSol/assets/5525742/fb85ace6-8733-4e62-9711-9d7fc45e7b0f

So I changed ```smallest_size``` from 0.1 to 0.01.
Model seems to work well with ```mmg``` right now.
<img width="300" alt="diffusion" src="https://github.com/tan2/DynEarthSol/assets/5525742/c27e722a-e001-479f-8957-0483a63437e9">

Movie 0 - 60 kyr
https://github.com/tan2/DynEarthSol/assets/5525742/6cb1808a-2dd3-4edd-ba7a-3ec82d886808

In the future, a further comparation between the models with ```Triangle``` and ```mmg``` is needed.
